### ISSUE TITLE
NPE in ZoneTopologyListener.parseConnectedDeviceNames

### ISSUE THREAD

**Issue by rhierlmeier** [KilianB/Java-Sonos-Controller#8]
`Exception in thread "Thread-3" java.lang.NullPointerException
        at com.github.kilianB.sonos.listener.ZoneTopologyListener.parseConnectedDeviceNames(ZoneTopologyListener.java:89)
        at com.github.kilianB.sonos.listener.ZoneTopologyListener.initialEventReceived(ZoneTopologyListener.java:54)
        at com.github.kilianB.uPnPClient.UPnPDevice.parseUPnPEvent(UPnPDevice.java:543)
        at com.github.kilianB.uPnPClient.UPnPDevice.lambda$new$1(UPnPDevice.java:456)
        at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by KilianB** [comment]
https://github.com/KilianB/Java-Sonos-Controller/blob/8588b20a2c98b89b510b1e07bd7d98e372b4049a/src/main/java/com/github/kilianB/sonos/listener/ZoneTopologyListener.java#L89 

Could you please print out the upnp event and property this is happening for?

**Comment by rhierlmeier** [comment]
Sorry I cannot repoduce the problem. It happened in a docker container. The upnp event came from a Sonos One.
